config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks, except: [:show] do 
    collection do 
      get :export_csv
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true
  validates :done, inclusion: { in: [true, false] }

  belongs_to :parent, class_name: "Task", optional: true
  has_many :sub_tasks, class_name: "Task", foreign_key: :parent_id, dependent: :destroy

  scope :only_parents, -> {where(parent_id: nil)}

  def symbol
    case status
    when "pending" then "»"
    when "done" then "✓"
    when "expired" then "×"
    end
  end

  def css_color
    case status
    when "pending" then "primary"
    when "done" then "success"
    when "expired" then "danger"
    end
  end

  def parent?
    parent_id.nil?
  end

  def sub_tasks?
    !parent?
  end

  private

  def status 
    return "done" if done?

    due_date.past? ? "expired" : "pending"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Exportable
  before_action :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == "eve123"
    end
  end
end

app/controllers/concerns/exportable.rb
require "csv"

module Exportable
  extend ActiveSupport::Concern

  def export_csv
    headers = ["Descrição", "Finalizada?", "ID da tarefa pai", "Criada em", "Atualizada em"]

    csv = CSV.generate(write_headers: true, headers: headers) do |row|
      Task.all.each do |task|
        row << [
          task.description,
          task.done? ? "Sim" : "Não",
          task.parent_id,
          task.created_at,
          task.updated_at
        ]
      end
    end

    send_data csv, type: "text/csv; charset=utf-8; header=present", disposition: "attachment; filename=tarefas.csv"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ edit update destroy ]

  def index
    @tasks = Task.only_parents.order(:due_date)
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: "Tarefa criada com sucesso." }
      else
        flash.now[:alert] = @task.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity  }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "Tarefa foi atualizada com sucesso." }
      else
        flash.now[:alert] = @task.errors.full_messages.to_sentence
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end 

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Tarefa foi removida com sucesso." }
    end
  end


  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :due_date, :done, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Task Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>

  <body style="overflow:hidden;">
    <div class="d-flex h-100 align-items-center justify-content-center row bg-primary bg-image">
      <main class="col-11 col-md-10 col-lg-8 shadow-lg p-5 mb-5 bg-white rounded" style="opacity: 0.94;">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
          </div>
        <% end %>

        <%= yield %>

      </main>
    </div>

    <!-- Bootstrap scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <%= form.hidden_field :parent_id, value: task.parent_id || params[:parent_id] %>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div class="form-group">
    <%= form.check_box :done %>
    <%= form.label :done %>
  </div>

  <%= form.submit class: "btn btn-primary", data: {disable_with: "Salvando..."} %>

  <%= link_to "Cancelar", tasks_path, class: "btn btn-light" %>
<% end %>

app/views/tasks/_table_row.html.erb
<tr class='<%= task.parent? ? "border-top" : "" %>'>

  <td style="font-weight: bold;" class="<%= task.sub_tasks? ? "pl-5" : "" %>">
    <span class="text-<%= task.css_color %> mr-8"><%= task.symbol %></span>

    <% if task.done? %>
      <s class="text-muted"><%= task.description %></s>
    <% else %>
      <%= task.description %>   
    <% end %>
  </td>

  <td>
    <% if(task.due_date) %>
      <%= I18n.l( task.due_date ) %>
    <% else %>
      Sem prazo
    <% end %>
  </td>

  <td class="text-right pr-0">
    <% if task.parent? %>
      <%= link_to "+ Sub-tarefa", new_task_path(parent_id: task.id), class: "btn btn-success btn-sm" %>
    <% end %>

    <%= link_to "Editar", edit_task_path(task), class: "btn btn-secondary btn-sm" %>
    <%= link_to "Apagar", task, data: {turbo_method: :delete, turbo_confirm: "Você tem certeza?"}, class: "btn btn-danger btn-sm", style: "display: inline-block;" %>
  </td>
</tr>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= task.done %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1 class="display-4">Editar <%= @task.parent? ? "tarefa" : "sub-tarefa"  %></h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="row mb-2">
  <div class="col-8">
    <h1 class="display-4 font-weight-normal">Tarefas</h1>
  </div>

  <div class="col-4 mt-4 text-right">
    <%= link_to '+ Tarefa', new_task_path, class: 'btn btn-success' %>
    <%= link_to 'Exportar CSV', export_csv_tasks_path, class: 'btn btn-info' %>
  </div>
</div>

<% if @tasks.any? %>
  <table class="table table-borderless">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Prazo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <%= render "table_row", task: task %>

        <% task.sub_tasks.order(:due_date).each do |sub_task| %>
          <%= render "table_row", task: sub_task %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Nenhuma tarefa foi cadastrada ainda.</p>
<% end %>

app/views/tasks/new.html.erb
<h1 class="display-4">
  Nova <%= params[:parent_id].present? ? "sub-tarefa" : "tarefa" %>
</h1>

<%= render "form", task: @task %>

<br>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>